#! /bin/sh

# Setup the build environment
PATH=$PATH:/usr/local/bin
PGDIR=/usr/local/pgsql
WXDIR=/usr/local
export PATH PGDIR WXDIR

# Cleanup
cd /usr/local/src/pgadmin3
rm -rf ./pgadmin3
rm -rf ./src

# CVS update
/usr/bin/cvs update -d -C

# Bootstrap and make a source tarball
/bin/sh bootstrap
cd /usr/local/src
/bin/tar czf /usr/local/apache/htdocs/src/pgadmin3-`/usr/bin/date +%Y%m%d`.tar.gz pgadmin3
cd /usr/local/src/pgadmin3

# Now the build
./configure --with-pgsql=$PGDIR --with-wx=$WXDIR
make all
/usr/bin/strip src/pgAdmin3

# Build a clean distro
mkdir ./pgadmin3
mkdir ./pgadmin3/ui
mkdir ./pgadmin3/ui/common
cp ./src/pgAdmin3 ./pgadmin3
cp ./src/tips.txt ./pgadmin3
cp ./src/ui/common/*.xrc ./pgadmin3/ui/common

# Build the snapshot and file it.
/bin/tar czf /usr/local/apache/htdocs/linux/pgadmin3-`/usr/bin/date +%Y%m%d`-`/usr/bin/uname -s`-`/usr/bin/uname -r`.tar.gz pgadmin3
ln -s -f /usr/local/apache/htdocs/linux/pgadmin3-`/usr/bin/date +%Y%m%d`-`/usr/bin/uname -s`-`/usr/bin/uname -r`.tar.gz /usr/local/apache/htdocs/linux/pgadmin3-Alpha-`/usr/bin/uname -s`-`/usr/bin/uname -r`.tar.gz
