#!/bin/sh

#######################################################################
#
# pgAdmin III - PostgreSQL Tools
# Copyright (C) 2002 - 2016, The pgAdmin Development Team
# This software is released under the PostgreSQL Licence
#
# embed-xrc - convert xrc files to c++ files
#
#######################################################################

echo Rebuilding xrcdialogs.cpp...

wxrc -c -o $( dirname $0 )/xrcDialogs.cpp.new $( dirname $0 )/*.xrc

diff $( dirname $0 )/xrcDialogs.cpp.new $( dirname $0 )/xrcDialogs.cpp 1> /dev/null
rc=$?

if [ x"$rc" != x"0" ] ; then
    mv $( dirname $0 )/xrcDialogs.cpp.new $( dirname $0 )/xrcDialogs.cpp
else
    rm $( dirname $0 )/xrcDialogs.cpp.new
fi
