#######################################################################
#
# pgAdmin III - PostgreSQL Tools
# $Id$
# Copyright (C) 2002 - 2007, The pgAdmin Development Team
# This software is released under the Artistic Licence
#
# module.mk - pgadmin/include/images/ Makefile fragment
#
#######################################################################

pgadmin3_SOURCES += \
	$(srcdir)/include/images/aggregate-sm.xpm \
	$(srcdir)/include/images/aggregate.xpm \
	$(srcdir)/include/images/aggregates.xpm \
	$(srcdir)/include/images/back.xpm \
	$(srcdir)/include/images/backup.xpm \
	$(srcdir)/include/images/baddatabase.xpm \
	$(srcdir)/include/images/cast-sm.xpm \
	$(srcdir)/include/images/cast.xpm \
	$(srcdir)/include/images/casts.xpm \
	$(srcdir)/include/images/catalog.xpm \
	$(srcdir)/include/images/catalog-sm.xpm \
	$(srcdir)/include/images/catalogs.xpm \
	$(srcdir)/include/images/catalogobject.xpm \
	$(srcdir)/include/images/catalogobject-sm.xpm \
	$(srcdir)/include/images/catalogobjects.xpm \
	$(srcdir)/include/images/check.xpm \
	$(srcdir)/include/images/checked.xpm \
	$(srcdir)/include/images/clearAll.xpm \
	$(srcdir)/include/images/clip_copy.xpm \
	$(srcdir)/include/images/clip_cut.xpm \
	$(srcdir)/include/images/clip_paste.xpm \
	$(srcdir)/include/images/closeddatabase-sm.xpm \
	$(srcdir)/include/images/closeddatabase.xpm \
	$(srcdir)/include/images/column-sm.xpm \
	$(srcdir)/include/images/column.xpm \
	$(srcdir)/include/images/columns.xpm \
	$(srcdir)/include/images/connect.xpm \
	$(srcdir)/include/images/constraints.xpm \
	$(srcdir)/include/images/continue.xpm \
	$(srcdir)/include/images/conversion.xpm \
	$(srcdir)/include/images/conversions.xpm \
	$(srcdir)/include/images/create.xpm \
	$(srcdir)/include/images/database-sm.xpm \
	$(srcdir)/include/images/database.xpm \
	$(srcdir)/include/images/databases.xpm \
	$(srcdir)/include/images/delete.xpm \
	$(srcdir)/include/images/dnd_copy.xpm \
	$(srcdir)/include/images/dnd_move.xpm \
	$(srcdir)/include/images/dnd_none.xpm \
	$(srcdir)/include/images/domain-sm.xpm \
	$(srcdir)/include/images/domain.xpm \
	$(srcdir)/include/images/domains.xpm \
	$(srcdir)/include/images/drop.xpm \
	$(srcdir)/include/images/edit_clear.xpm \
	$(srcdir)/include/images/edit_find.xpm \
	$(srcdir)/include/images/edit_redo.xpm \
	$(srcdir)/include/images/edit_undo.xpm \
	$(srcdir)/include/images/elephant32.xpm \
	$(srcdir)/include/images/elephant48.xpm \
	$(srcdir)/include/images/enumeration.xpm \
	$(srcdir)/include/images/enumerations.xpm \
	$(srcdir)/include/images/ex_aggregate.xpm \
	$(srcdir)/include/images/ex_append.xpm \
	$(srcdir)/include/images/ex_bmp_heap.xpm \
	$(srcdir)/include/images/ex_bmp_index.xpm \
	$(srcdir)/include/images/ex_group.xpm \
	$(srcdir)/include/images/ex_hash.xpm \
	$(srcdir)/include/images/ex_index_scan.xpm \
	$(srcdir)/include/images/ex_join.xpm \
	$(srcdir)/include/images/ex_limit.xpm \
	$(srcdir)/include/images/ex_materialize.xpm \
	$(srcdir)/include/images/ex_merge.xpm \
	$(srcdir)/include/images/ex_nested.xpm \
	$(srcdir)/include/images/ex_result.xpm \
	$(srcdir)/include/images/ex_scan.xpm \
	$(srcdir)/include/images/ex_seek.xpm \
	$(srcdir)/include/images/ex_setop.xpm \
	$(srcdir)/include/images/ex_sort.xpm \
	$(srcdir)/include/images/ex_subplan.xpm \
	$(srcdir)/include/images/ex_tid_scan.xpm \
	$(srcdir)/include/images/ex_unique.xpm \
	$(srcdir)/include/images/ex_unknown.xpm \
	$(srcdir)/include/images/favourite.xpm \
	$(srcdir)/include/images/file_new.xpm \
	$(srcdir)/include/images/file_open.xpm \
	$(srcdir)/include/images/file_save.xpm \
	$(srcdir)/include/images/folder.xpm \
	$(srcdir)/include/images/foreignkey.xpm \
	$(srcdir)/include/images/forward.xpm \
	$(srcdir)/include/images/function.xpm \
	$(srcdir)/include/images/functions.xpm \
	$(srcdir)/include/images/group.xpm \
	$(srcdir)/include/images/groups.xpm \
	$(srcdir)/include/images/help.xpm \
	$(srcdir)/include/images/help2.xpm \
	$(srcdir)/include/images/hint.xpm \
	$(srcdir)/include/images/hint2.xpm \
	$(srcdir)/include/images/index.xpm \
	$(srcdir)/include/images/indexes.xpm \
	$(srcdir)/include/images/job.xpm \
	$(srcdir)/include/images/jobdisabled.xpm \
	$(srcdir)/include/images/jobs.xpm \
	$(srcdir)/include/images/key.xpm \
	$(srcdir)/include/images/language-sm.xpm \
	$(srcdir)/include/images/language.xpm \
	$(srcdir)/include/images/languages.xpm \
	$(srcdir)/include/images/loginroles.xpm \
	$(srcdir)/include/images/namespace-sm.xpm \
	$(srcdir)/include/images/namespace.xpm \
	$(srcdir)/include/images/namespaces.xpm \
	$(srcdir)/include/images/operator.xpm \
	$(srcdir)/include/images/operators.xpm \
	$(srcdir)/include/images/operatorclass.xpm \
	$(srcdir)/include/images/operatorclasses.xpm \
	$(srcdir)/include/images/operatorfamily.xpm \
	$(srcdir)/include/images/operatorfamilies.xpm \
	$(srcdir)/include/images/package.xpm \
	$(srcdir)/include/images/packages.xpm \
	$(srcdir)/include/images/pgAdmin3.xpm \
	$(srcdir)/include/images/primarykey.xpm \
	$(srcdir)/include/images/procedures.xpm \
	$(srcdir)/include/images/procedure.xpm \
	$(srcdir)/include/images/properties.xpm \
	$(srcdir)/include/images/property.xpm \
	$(srcdir)/include/images/query_cancel.xpm \
	$(srcdir)/include/images/query_execfile.xpm \
	$(srcdir)/include/images/query_execute.xpm \
	$(srcdir)/include/images/query_explain.xpm \
	$(srcdir)/include/images/readdata.xpm \
	$(srcdir)/include/images/refresh.xpm \
	$(srcdir)/include/images/reload.xpm \
	$(srcdir)/include/images/restore.xpm \
	$(srcdir)/include/images/roles.xpm \
	$(srcdir)/include/images/rule.xpm \
	$(srcdir)/include/images/rules.xpm \
	$(srcdir)/include/images/schedule.xpm \
	$(srcdir)/include/images/schedules.xpm \
	$(srcdir)/include/images/sequence-repl.xpm \
	$(srcdir)/include/images/sequence.xpm \
	$(srcdir)/include/images/sequences.xpm \
	$(srcdir)/include/images/server-sm.xpm \
	$(srcdir)/include/images/server.xpm \
	$(srcdir)/include/images/serverbad-sm.xpm \
	$(srcdir)/include/images/serverbad.xpm \
	$(srcdir)/include/images/servers.xpm \
	$(srcdir)/include/images/setBreak.xpm \
	$(srcdir)/include/images/slcluster.xpm \
	$(srcdir)/include/images/slclusters.xpm \
	$(srcdir)/include/images/sllisten.xpm \
	$(srcdir)/include/images/sllistens.xpm \
	$(srcdir)/include/images/slnode-disabled.xpm \
	$(srcdir)/include/images/slnode-local.xpm \
	$(srcdir)/include/images/slnode.xpm \
	$(srcdir)/include/images/slnodes.xpm \
	$(srcdir)/include/images/slpath.xpm \
	$(srcdir)/include/images/slpaths.xpm \
	$(srcdir)/include/images/slset.xpm \
	$(srcdir)/include/images/slset2.xpm \
	$(srcdir)/include/images/slsets.xpm \
	$(srcdir)/include/images/slsubscription.xpm \
	$(srcdir)/include/images/slsubscription2.xpm \
	$(srcdir)/include/images/slsubscriptions.xpm \
	$(srcdir)/include/images/sortfilter.xpm \
	$(srcdir)/include/images/splash.xpm \
	$(srcdir)/include/images/sql.xpm \
	$(srcdir)/include/images/statistics.xpm \
	$(srcdir)/include/images/step.xpm \
	$(srcdir)/include/images/steps.xpm \
	$(srcdir)/include/images/stepInto.xpm \
	$(srcdir)/include/images/stepOver.xpm \
	$(srcdir)/include/images/stop.xpm \
	$(srcdir)/include/images/storedata.xpm \
	$(srcdir)/include/images/synonym.xpm \
	$(srcdir)/include/images/synonyms.xpm \
	$(srcdir)/include/images/table-repl-sm.xpm \
	$(srcdir)/include/images/table-repl.xpm \
	$(srcdir)/include/images/table-sm.xpm \
	$(srcdir)/include/images/table.xpm \
	$(srcdir)/include/images/tables.xpm \
	$(srcdir)/include/images/tablespace.xpm \
	$(srcdir)/include/images/tablespaces.xpm \
	$(srcdir)/include/images/trigger.xpm \
	$(srcdir)/include/images/triggerfunction.xpm \
	$(srcdir)/include/images/triggerfunctions.xpm \
	$(srcdir)/include/images/triggers.xpm \
	$(srcdir)/include/images/type.xpm \
	$(srcdir)/include/images/types.xpm \
	$(srcdir)/include/images/unchecked.xpm \
	$(srcdir)/include/images/unique.xpm \
	$(srcdir)/include/images/user.xpm \
	$(srcdir)/include/images/users.xpm \
	$(srcdir)/include/images/vacuum.xpm \
	$(srcdir)/include/images/view-sm.xpm \
	$(srcdir)/include/images/view.xpm \
	$(srcdir)/include/images/viewdata.xpm \
	$(srcdir)/include/images/viewfiltereddata.xpm \
	$(srcdir)/include/images/views.xpm

EXTRA_DIST += \
        $(srcdir)/include/images/module.mk \
	$(srcdir)/include/images/pgAdmin3.ico
