#######################################################################
#
# pgAdmin III - PostgreSQL Tools
# 
# Copyright (C) 2002 - 2011, The pgAdmin Development Team
# This software is released under the PostgreSQL Licence
#
# module.mk -	 $(srcdir)/include/images/ Makefile fragment
#
#######################################################################

pgadmin3_SOURCES += \
	$(srcdir)/include/images/aggregate-sm.png \
	$(srcdir)/include/images/aggregate.png \
	$(srcdir)/include/images/aggregates.png \
	$(srcdir)/include/images/back.png \
	$(srcdir)/include/images/backup.png \
	$(srcdir)/include/images/baddatabase.png \
	$(srcdir)/include/images/cast-sm.png \
	$(srcdir)/include/images/cast.png \
	$(srcdir)/include/images/casts.png \
	$(srcdir)/include/images/catalog.png \
	$(srcdir)/include/images/catalog-sm.png \
	$(srcdir)/include/images/catalogs.png \
	$(srcdir)/include/images/catalogobject.png \
	$(srcdir)/include/images/catalogobject-sm.png \
	$(srcdir)/include/images/catalogobjects.png \
	$(srcdir)/include/images/check.png \
	$(srcdir)/include/images/checked.png \
	$(srcdir)/include/images/clearAll.png \
	$(srcdir)/include/images/clip_copy.png \
	$(srcdir)/include/images/clip_cut.png \
	$(srcdir)/include/images/clip_paste.png \
	$(srcdir)/include/images/closeddatabase-sm.png \
	$(srcdir)/include/images/closeddatabase.png \
	$(srcdir)/include/images/column-sm.png \
	$(srcdir)/include/images/column.png \
	$(srcdir)/include/images/columns.png \
	$(srcdir)/include/images/configuration.png \
	$(srcdir)/include/images/configurations.png \
	$(srcdir)/include/images/connect.png \
	$(srcdir)/include/images/constraints.png \
	$(srcdir)/include/images/continue.png \
	$(srcdir)/include/images/conversion.png \
	$(srcdir)/include/images/conversions.png \
	$(srcdir)/include/images/create.png \
	$(srcdir)/include/images/database-sm.png \
	$(srcdir)/include/images/database.png \
	$(srcdir)/include/images/databases.png \
	$(srcdir)/include/images/debugger.png \
	$(srcdir)/include/images/delete.png \
	$(srcdir)/include/images/dictionary.png \
	$(srcdir)/include/images/dictionaries.png \
	$(srcdir)/include/images/disabled.png \
	$(srcdir)/include/images/dnd_copy.png \
	$(srcdir)/include/images/dnd_move.png \
	$(srcdir)/include/images/dnd_none.png \
	$(srcdir)/include/images/domain-sm.png \
	$(srcdir)/include/images/domain.png \
	$(srcdir)/include/images/domains.png \
	$(srcdir)/include/images/extension-sm.png \
	$(srcdir)/include/images/extension.png \
	$(srcdir)/include/images/extensions.png \
	$(srcdir)/include/images/down.png \
	$(srcdir)/include/images/drop.png \
	$(srcdir)/include/images/edit_clear.png \
	$(srcdir)/include/images/edit_find.png \
	$(srcdir)/include/images/edit_redo.png \
	$(srcdir)/include/images/edit_undo.png \
	$(srcdir)/include/images/enumeration.png \
	$(srcdir)/include/images/enumerations.png \
	$(srcdir)/include/images/ex_aggregate.png \
	$(srcdir)/include/images/ex_append.png \
	$(srcdir)/include/images/ex_bmp_heap.png \
	$(srcdir)/include/images/ex_bmp_index.png \
	$(srcdir)/include/images/ex_cte_scan.png \
	$(srcdir)/include/images/ex_group.png \
	$(srcdir)/include/images/ex_hash.png \
	$(srcdir)/include/images/ex_hash_anti_join.png \
	$(srcdir)/include/images/ex_hash_semi_join.png \
	$(srcdir)/include/images/ex_hash_setop_except.png \
	$(srcdir)/include/images/ex_hash_setop_except_all.png \
	$(srcdir)/include/images/ex_hash_setop_intersect.png \
	$(srcdir)/include/images/ex_hash_setop_intersect_all.png \
	$(srcdir)/include/images/ex_hash_setop_unknown.png \
	$(srcdir)/include/images/ex_index_scan.png \
	$(srcdir)/include/images/ex_join.png \
	$(srcdir)/include/images/ex_limit.png \
	$(srcdir)/include/images/ex_materialize.png \
	$(srcdir)/include/images/ex_merge.png \
	$(srcdir)/include/images/ex_merge_anti_join.png \
	$(srcdir)/include/images/ex_merge_semi_join.png \
	$(srcdir)/include/images/ex_nested.png \
	$(srcdir)/include/images/ex_nested_loop_anti_join.png \
	$(srcdir)/include/images/ex_nested_loop_semi_join.png \
	$(srcdir)/include/images/ex_recursive_union.png \
	$(srcdir)/include/images/ex_result.png \
	$(srcdir)/include/images/ex_scan.png \
	$(srcdir)/include/images/ex_seek.png \
	$(srcdir)/include/images/ex_setop.png \
	$(srcdir)/include/images/ex_sort.png \
	$(srcdir)/include/images/ex_subplan.png \
	$(srcdir)/include/images/ex_tid_scan.png \
	$(srcdir)/include/images/ex_unique.png \
	$(srcdir)/include/images/ex_unknown.png \
	$(srcdir)/include/images/ex_window_aggregate.png \
	$(srcdir)/include/images/ex_worktable_scan.png \
	$(srcdir)/include/images/exclude.png \
	$(srcdir)/include/images/favourite.png \
	$(srcdir)/include/images/file_new.png \
	$(srcdir)/include/images/file_open.png \
	$(srcdir)/include/images/file_save.png \
	$(srcdir)/include/images/folder.png \
	$(srcdir)/include/images/foreigndatawrapper.png \
	$(srcdir)/include/images/foreigndatawrapper-sm.png \
	$(srcdir)/include/images/foreigndatawrappers.png \
	$(srcdir)/include/images/foreignkey.png \
	$(srcdir)/include/images/foreignkeybad.png \
	$(srcdir)/include/images/foreignserver.png \
	$(srcdir)/include/images/foreignserver-sm.png \
	$(srcdir)/include/images/foreignservers.png \
	$(srcdir)/include/images/foreigntable.png \
	$(srcdir)/include/images/foreigntables.png \
	$(srcdir)/include/images/forward.png \
	$(srcdir)/include/images/function.png \
	$(srcdir)/include/images/functions.png \
	$(srcdir)/include/images/gqbAdd.png \
	$(srcdir)/include/images/gqbAddRest.png \
	$(srcdir)/include/images/gqbColNotSel.png \
	$(srcdir)/include/images/gqbColSel.png \
	$(srcdir)/include/images/gqbDown.png \
	$(srcdir)/include/images/gqbDownBottom.png \
	$(srcdir)/include/images/gqbJoin.png \
	$(srcdir)/include/images/gqbJoinCursor.png \
	$(srcdir)/include/images/gqbOrderAdd.png \
	$(srcdir)/include/images/gqbOrderAddAll.png \
	$(srcdir)/include/images/gqbOrderRemove.png \
	$(srcdir)/include/images/gqbOrderRemoveAll.png \
	$(srcdir)/include/images/gqbRemove.png \
	$(srcdir)/include/images/gqbRemoveRest.png \
	$(srcdir)/include/images/gqbUp.png \
	$(srcdir)/include/images/gqbUpTop.png \
	$(srcdir)/include/images/group.png \
	$(srcdir)/include/images/groups.png \
	$(srcdir)/include/images/help.png \
	$(srcdir)/include/images/help2.png \
	$(srcdir)/include/images/hint.png \
	$(srcdir)/include/images/hint2.png \
	$(srcdir)/include/images/index.png \
	$(srcdir)/include/images/indexes.png \
	$(srcdir)/include/images/job.png \
	$(srcdir)/include/images/jobdisabled.png \
	$(srcdir)/include/images/jobs.png \
	$(srcdir)/include/images/key.png \
	$(srcdir)/include/images/language-sm.png \
	$(srcdir)/include/images/language.png \
	$(srcdir)/include/images/languages.png \
	$(srcdir)/include/images/loginroles.png \
	$(srcdir)/include/images/namespace-sm.png \
	$(srcdir)/include/images/namespace.png \
	$(srcdir)/include/images/namespaces.png \
	$(srcdir)/include/images/operator.png \
	$(srcdir)/include/images/operators.png \
	$(srcdir)/include/images/operatorclass.png \
	$(srcdir)/include/images/operatorclasses.png \
	$(srcdir)/include/images/operatorfamily.png \
	$(srcdir)/include/images/operatorfamilies.png \
	$(srcdir)/include/images/package.png \
	$(srcdir)/include/images/packages.png \
	$(srcdir)/include/images/parser.png \
	$(srcdir)/include/images/parsers.png \
	$(srcdir)/include/images/plugins.png \
	$(srcdir)/include/images/pgAdmin3.png \
	$(srcdir)/include/images/pgAdmin3-16.png \
	$(srcdir)/include/images/pgAdmin3-32.png \
	$(srcdir)/include/images/primarykey.png \
	$(srcdir)/include/images/procedures.png \
	$(srcdir)/include/images/procedure.png \
	$(srcdir)/include/images/properties.png \
	$(srcdir)/include/images/property.png \
	$(srcdir)/include/images/query_cancel.png \
	$(srcdir)/include/images/query_execfile.png \
	$(srcdir)/include/images/query_execute.png \
	$(srcdir)/include/images/query_explain.png \
	$(srcdir)/include/images/query_pgscript.png \
	$(srcdir)/include/images/readdata.png \
	$(srcdir)/include/images/refresh.png \
	$(srcdir)/include/images/reload.png \
	$(srcdir)/include/images/restore.png \
	$(srcdir)/include/images/roles.png \
	$(srcdir)/include/images/rule.png \
	$(srcdir)/include/images/rulebad.png \
	$(srcdir)/include/images/rules.png \
	$(srcdir)/include/images/schedule.png \
	$(srcdir)/include/images/schedules.png \
	$(srcdir)/include/images/sequence-repl.png \
	$(srcdir)/include/images/sequence.png \
	$(srcdir)/include/images/sequences.png \
	$(srcdir)/include/images/server-sm.png \
	$(srcdir)/include/images/server.png \
	$(srcdir)/include/images/serverbad-sm.png \
	$(srcdir)/include/images/serverbad.png \
	$(srcdir)/include/images/servers.png \
	$(srcdir)/include/images/setBreak.png \
	$(srcdir)/include/images/slcluster.png \
	$(srcdir)/include/images/slclusters.png \
	$(srcdir)/include/images/sllisten.png \
	$(srcdir)/include/images/sllistens.png \
	$(srcdir)/include/images/slnode-disabled.png \
	$(srcdir)/include/images/slnode-local.png \
	$(srcdir)/include/images/slnode.png \
	$(srcdir)/include/images/slnodes.png \
	$(srcdir)/include/images/slpath.png \
	$(srcdir)/include/images/slpaths.png \
	$(srcdir)/include/images/slset.png \
	$(srcdir)/include/images/slset2.png \
	$(srcdir)/include/images/slsets.png \
	$(srcdir)/include/images/slsubscription.png \
	$(srcdir)/include/images/slsubscription2.png \
	$(srcdir)/include/images/slsubscriptions.png \
	$(srcdir)/include/images/sortfilter.png \
	$(srcdir)/include/images/splash.png \
	$(srcdir)/include/images/sql.png \
	$(srcdir)/include/images/sql-16.png \
	$(srcdir)/include/images/sql-32.png \
	$(srcdir)/include/images/statistics.png \
	$(srcdir)/include/images/step.png \
	$(srcdir)/include/images/steps.png \
	$(srcdir)/include/images/stepInto.png \
	$(srcdir)/include/images/stepOver.png \
	$(srcdir)/include/images/stop.png \
	$(srcdir)/include/images/storedata.png \
	$(srcdir)/include/images/synonym.png \
	$(srcdir)/include/images/synonyms.png \
	$(srcdir)/include/images/table-repl-sm.png \
	$(srcdir)/include/images/table-repl.png \
	$(srcdir)/include/images/table-sm.png \
	$(srcdir)/include/images/table.png \
	$(srcdir)/include/images/tables.png \
	$(srcdir)/include/images/tablespace.png \
	$(srcdir)/include/images/tablespaces.png \
	$(srcdir)/include/images/template.png \
	$(srcdir)/include/images/templates.png \
	$(srcdir)/include/images/terminate_backend.png \
	$(srcdir)/include/images/textsearch.png \
	$(srcdir)/include/images/trigger.png \
	$(srcdir)/include/images/triggerbad.png \
	$(srcdir)/include/images/triggerfunction.png \
	$(srcdir)/include/images/triggerfunctions.png \
	$(srcdir)/include/images/triggers.png \
	$(srcdir)/include/images/type.png \
	$(srcdir)/include/images/types.png \
	$(srcdir)/include/images/uncheck.png \
	$(srcdir)/include/images/unchecked.png \
	$(srcdir)/include/images/unique.png \
	$(srcdir)/include/images/up.png \
	$(srcdir)/include/images/user.png \
	$(srcdir)/include/images/usermapping.png \
	$(srcdir)/include/images/usermapping-sm.png \
	$(srcdir)/include/images/usermappings.png \
	$(srcdir)/include/images/users.png \
	$(srcdir)/include/images/vacuum.png \
	$(srcdir)/include/images/variable.png \
	$(srcdir)/include/images/variables.png \
	$(srcdir)/include/images/view-sm.png \
	$(srcdir)/include/images/view.png \
	$(srcdir)/include/images/viewdata.png \
	$(srcdir)/include/images/viewfiltereddata.png \
	$(srcdir)/include/images/views.png \
	$(srcdir)/include/images/ex_broadcast_motion.png \
	$(srcdir)/include/images/ex_redistribute_motion.png \
	$(srcdir)/include/images/ex_gather_motion.png \
	$(srcdir)/include/images/exttable-sm.png \
	$(srcdir)/include/images/exttables.png \
	$(srcdir)/include/images/exttable.png

EXTRA_DIST += \
	$(srcdir)/include/images/module.mk \
	$(srcdir)/include/images/pgAdmin3.ico \
	$(srcdir)/include/images/sql.ico

