#!/bin/sh

if [ $# -ne 1 ]
then
  echo "usage: $0 <wxMAC Source directory>"
  exit 1
fi

cd $1

cd contrib


make clean
cd ..
make clean
./configure --with-mac --enable-universal_binary --with-macosx-sdk=/Developer/SDKs/MacOSX10.5.sdk --with-macosx-version-min=10.5 --enable-unicode --enable-mimetype=no --disable-shared --enable-debug
make all
make install
cd contrib
make all
make install


make clean
cd ..
make clean
./configure --with-mac --enable-universal_binary --with-macosx-sdk=/Developer/SDKs/MacOSX10.5.sdk --with-macosx-version-min=10.5 --enable-unicode --enable-mimetype=no --disable-shared --disable-debug
make all
make install
cd contrib
make all
make install


make clean
cd ..
make clean
./configure --with-mac --enable-universal_binary --with-macosx-sdk=/Developer/SDKs/MacOSX10.5.sdk --with-macosx-version-min=10.5 --enable-unicode --enable-mimetype=no --enable-shared --enable-debug
make all
make install
cd contrib
make all
make install


make clean
cd .. 
make clean
./configure --with-mac --enable-universal_binary --with-macosx-sdk=/Developer/SDKs/MacOSX10.5.sdk --with-macosx-version-min=10.5 --enable-unicode --enable-mimetype=no --enable-shared --disable-debug
make all
make install
cd contrib
make all
make install

cd ../utils/hhp2cached
make all
make install
cd ../wxrc
make all
make install
