#! /bin/sh

#######################################################################
#
# pgAdmin III - PostgreSQL Tools
# Copyright (C) 2002 - 2004, The pgAdmin Development Team
# This software is released under the Artistic Licence
#
# build-release - Build a Slackware release
#
#######################################################################

if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <version>"
	exit
fi

# Setup the build environment
PATH=$PATH:/usr/local/bin
PGDIR=/usr/local/pgsql
WXDIR=/usr/local/
export PATH PGDIR WXDIR

# Configure for the local OS
./configure --prefix=/usr/local/src/pgadmin3/slackpack/usr \
	--with-pgsql=$PGDIR --with-wx=$WXDIR --enable-static --enable-release \
	--datadir=/usr/share

# Now make the binary build
make all
/usr/bin/strip src/pgadmin3

# Build a clean distro
if [ -x src/pgadmin3 ]; then

	# Use the build system
	make install
	
	# And tweak for Slackware
	mkdir -p ./slackpack/opt/kde/share/applnk/Development
	mkdir -p ./slackpack/usr/share
	mkdir -p ./slackpack/install
	mv /usr/share/pgadmin3 ./slackpack/usr/share/
	cp ./pkg/pgadmin3.desktop ./slackpack/opt/kde/share/applnk/Development
	cp ./src/include/images/elephant48.xpm ./slackpack/usr/share/pgadmin3/pgadmin3.xpm
	echo "pgadmin3-$1: pgAdmin III - PostgreSQL Tools" >> ./slackpack/install/slack-desc
	echo "pgadmin3-$1: " >> ./slackpack/install/slack-desc
	echo "pgadmin3-$1: pgAdmin III is the most popular Open Source management tool for" >> ./slackpack/install/slack-desc
	echo "pgadmin3-$1: the PostgreSQL Object Relational Database Management System." >> ./slackpack/install/slack-desc
	echo "pgadmin3-$1: " >> ./slackpack/install/slack-desc
	echo "pgadmin3-$1: http://www.pgadmin.org/" >> ./slackpack/install/slack-desc
	echo "pgadmin3-$1: http://www.postgresql.org/" >> ./slackpack/install/slack-desc
	echo "pgadmin3-$1: " >> ./slackpack/install/slack-desc
	echo "pgadmin3-$1: " >> ./slackpack/install/slack-desc
	echo "pgadmin3-$1: " >> ./slackpack/install/slack-desc
	echo "pgadmin3-$1: " >> ./slackpack/install/slack-desc

	# Build the snapshot and file it.
	cd slackpack
	/sbin/makepkg --chown y pgadmin3-$1.tgz 
fi
