#! /bin/sh

# Setup the build environment
PATH=$PATH:/usr/local/bin
PGDIR=/usr/local/pgsql
WXDIR=/usr/local/
export PATH PGDIR WXDIR

# Cleanup
cd /usr/local/src/pgadmin3
rm -rf ./slackpack
rm -rf ./doc
rm -rf ./pkg
rm -rf ./src

# CVS update
/usr/bin/cvs update -d -C

# Bootstrap
/bin/sh bootstrap

# Configure for the local OS
./configure --prefix=/usr/local/src/pgadmin3/slackpack/usr \
	--with-pgsql=$PGDIR --with-wx=$WXDIR --enable-static --enable-debug

# Now make the binary build
make all
/usr/bin/strip src/pgadmin3

# Build a clean distro
if [ -x src/pgadmin3 ]; then

	# Use the build system
	make install
	
	# And tweak for Slackware
	mkdir -p ./slackpack/opt/kde/share/applnk/Development
	cp ./pkg/pgadmin3.desktop ./slackpack/opt/kde/share/applnk/Development
	cp ./src/include/images/elephant48.xpm ./slackpack/usr/share/pgadmin3/pgadmin3.xpm

	# Build the snapshot and file it.
	cd slackpack
	/sbin/makepkg --chown y pgadmin3.tgz 
	if [ -e pgadmin3.tgz ]; then
		cp pgadmin3.tgz /usr/local/apache/htdocs/snapshots/linux/slackware90/pgadmin3-`/usr/bin/date +%Y%m%d`.tgz
		ln -s -f linux/slackware90/pgadmin3-`/usr/bin/date +%Y%m%d`.tgz /usr/local/apache/htdocs/snapshots/pgadmin3-slackware90.tgz
		cp ../pkg/slackware/slack-desc /usr/local/apache/htdocs/snapshots/linux/slackware90/pgadmin3-`/usr/bin/date +%Y%m%d`.txt
	fi
fi
