#! /bin/sh

# Setup the build environment
PATH=$PATH:/usr/local/bin
PGDIR=/usr/local/pgsql
WXDIR=/usr/local/
export PATH PGDIR WXDIR

# Cleanup
cd /usr/local/src/pgadmin3
rm -rf ./slackpack
rm -rf ./doc
rm -rf ./pkg
rm -rf ./src

# CVS update
/usr/bin/cvs update -d -C

# Bootstrap
/bin/sh bootstrap

# Configure for the local OS
./configure --with-pgsql=$PGDIR --with-wx=$WXDIR --enable-static --enable-debug

# Now make the binary build
make all
/usr/bin/strip src/pgadmin3

# Build a clean distro
if [ -x src/pgadmin3 ]; then
	mkdir -p ./slackpack/usr/local/pgadmin3/bin
        mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/da_DK
	mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/de_DE
        mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/fa_IR
	mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/fr_FR
	mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/hr_HR
	mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/id_ID
	mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/it_IT
	mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/ja_JP
	mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/pl_PL
        mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/ro_RO
        mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/ru_RU
	mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/tr_TR
	mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/zh_CN
        mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/zh_TW
	mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/common
	mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/docs/en_US/images
	mkdir -p ./slackpack/usr/local/pgadmin3/share/pgadmin3/docs/en_US/pg

	cp ./src/pgadmin3 ./slackpack/usr/local/pgadmin3/bin/
	cp ./src/tips.txt ./slackpack/usr/local/pgadmin3/share/pgadmin3/
	cp ./src/ui/wxstd.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/
	cp ./src/ui/pgadmin3.lng ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/
        cp ./src/ui/da_DK/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/da_DK/
	cp ./src/ui/de_DE/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/de_DE/
	cp ./src/ui/fa_IR/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/fa_IR/
	cp ./src/ui/fr_FR/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/fr_FR/
	cp ./src/ui/hr_HR/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/hr_HR/
	cp ./src/ui/id_ID/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/id_ID/
	cp ./src/ui/it_IT/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/it_IT/
	cp ./src/ui/ja_JP/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/ja_JP/
	cp ./src/ui/pl_PL/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/pl_PL/
	cp ./src/ui/ro_RO/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/ro_RO/
        cp ./src/ui/ru_RU/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/ru_RU/
	cp ./src/ui/tr_TR/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/tr_TR/
	cp ./src/ui/zh_CN/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/zh_CN/
	cp ./src/ui/zh_TW/*.mo ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/zh_TW/
        cp ./src/ui/common/*.xrc ./slackpack/usr/local/pgadmin3/share/pgadmin3/ui/common/
        cp ./docs/en_US/*.html ./slackpack/usr/local/pgadmin3/share/pgadmin3/docs/en_US/
	cp ./docs/en_US/images/*.jpg ./slackpack/usr/local/pgadmin3/share/pgadmin3/docs/en_US/images/
	cp ./docs/en_US/pg/*.html ./slackpack/usr/local/pgadmin3/share/pgadmin3/docs/en_US/pg/
	cp ./docs/en_US/pg/*.gif ./slackpack/usr/local/pgadmin3/share/pgadmin3/docs/en_US/pg/
	cp ./docs/en_US/pg/*.css ./slackpack/usr/local/pgadmin3/share/pgadmin3/docs/en_US/pg/

	# Build the snapshot and file it.
	cd slackpack
	/sbin/makepkg --chown y pgadmin3.tgz 
	if [ -e pgadmin3.tgz ]; then
		cp pgadmin3.tgz /usr/local/apache/htdocs/snapshots/linux/slackware90/pgadmin3-`/usr/bin/date +%Y%m%d`.tgz
		ln -s -f linux/slackware90/pgadmin3-`/usr/bin/date +%Y%m%d`.tgz /usr/local/apache/htdocs/snapshots/pgadmin3-slackware90.tgz
		cp ../pkg/slackware/slack-desc /usr/local/apache/htdocs/snapshots/linux/slackware90/pgadmin3-`/usr/bin/date +%Y%m%d`.txt
	fi
fi
