//////////////////////////////////////////////////////////////////////////
//
// pgAdmin III - PostgreSQL Tools
// RCS-ID:      $Id$
// Copyright (C) 2002 - 2006, The pgAdmin Development Team
// This software is released under the Artistic Licence
//
// precomp.h - All header files for compilers supporting precompiled headers
//
//////////////////////////////////////////////////////////////////////////

#ifdef WX_PRECOMP

#include "agent/dlgJob.h"
#include "agent/dlgSchedule.h"
#include "agent/dlgStep.h"
#include "agent/pgaJob.h"
#include "agent/pgaSchedule.h"
#include "agent/pgaStep.h"
#include "copyright.h"
#include "ctl/calbox.h"
#include "ctl/ctlComboBox.h"
#include "ctl/ctlListView.h"
#include "ctl/ctlSQLBox.h"
#include "ctl/ctlSQLGrid.h"
#include "ctl/ctlSQLResult.h"
#include "ctl/ctlTree.h"
#include "ctl/timespin.h"
#include "ctl/xh_calb.h"
#include "ctl/xh_ctlcombo.h"
#include "ctl/xh_ctltree.h"
#include "ctl/xh_sqlbox.h"
#include "ctl/xh_timespin.h"
#include "ctlSecurityPanel.h"
#include "dlgAddFavourite.h"
#include "dlgAggregate.h"
#include "dlgCast.h"
#include "dlgCheck.h"
#include "dlgClasses.h"
#include "dlgColumn.h"
#include "dlgConnect.h"
#include "dlgConversion.h"
#include "dlgDatabase.h"
#include "dlgDomain.h"
#include "dlgEditGridOptions.h"
#include "dlgFindReplace.h"
#include "dlgForeignKey.h"
#include "dlgFunction.h"
#include "dlgGroup.h"
#include "dlgHbaConfig.h"
#include "dlgIndex.h"
#include "dlgIndexConstraint.h"
#include "dlgLanguage.h"
#include "dlgMainConfig.h"
#include "dlgManageFavourites.h"
#include "dlgOperator.h"
#include "dlgPgpassConfig.h"
#include "dlgProperty.h"
#include "dlgRole.h"
#include "dlgRule.h"
#include "dlgSchema.h"
#include "dlgSelectConnection.h"
#include "dlgSequence.h"
#include "dlgServer.h"
#include "dlgTable.h"
#include "dlgTablespace.h"
#include "dlgTrigger.h"
#include "dlgType.h"
#include "dlgUser.h"
#include "dlgView.h"
#include "explainCanvas.h"
#include "frmAbout.h"
#include "frmBackup.h"
#include "frmConfig.h"
#include "frmEditGrid.h"
#include "frmExport.h"
#include "frmGrantWizard.h"
#include "frmHbaConfig.h"
#include "frmHelp.h"
#include "frmHint.h"
#include "frmIndexcheck.h"
#include "frmMain.h"
#include "frmMainConfig.h"
#include "frmMaintenance.h"
#include "frmOptions.h"
#include "frmPassword.h"
#include "frmPgpassConfig.h"
#include "frmQuery.h"
#include "frmReport.h"
#include "frmRestore.h"
#include "frmSplash.h"
#include "frmStatus.h"
#include "menu.h"
//#include "nodes/parsenodes.h"
//#include "parser/keywords.h"
//#include "parser/parse.h"
#include "pgAdmin3.h"
#include "pgAggregate.h"
#include "pgCast.h"
#include "pgCheck.h"
#include "pgCollection.h"
#include "pgColumn.h"
#include "pgConn.h"
#include "pgConstraints.h"
#include "pgConversion.h"
#include "pgDatabase.h"
#include "pgDatatype.h"
#include "pgDomain.h"
#include "pgForeignKey.h"
#include "pgFunction.h"
#include "pgGroup.h"
#include "pgIndex.h"
#include "pgIndexConstraint.h"
#include "pgLanguage.h"
#include "pgObject.h"
#include "pgOperator.h"
#include "pgOperatorClass.h"
#include "pgQueryThread.h"
#include "pgRole.h"
#include "pgRule.h"
#include "pgSchema.h"
#include "pgSequence.h"
#include "pgServer.h"
#include "pgSet.h"
#include "pgTable.h"
#include "pgTablespace.h"
#include "pgTrigger.h"
#include "pgType.h"
#include "pgUser.h"
#include "pgView.h"
#include "pgfeatures.h"
#include "utils/factory.h"
#include "utils/favourites.h"
#include "utils/md5.h"
#include "utils/misc.h"
#include "utils/pgDefs.h"
#include "utils/pgconfig.h"
#include "utils/sysLogger.h"
#include "utils/sysProcess.h"
#include "utils/sysSettings.h"
#include "utils/utffile.h"
#include "version.h"
#include "wxgridsel.h"


#endif
