//////////////////////////////////////////////////////////////////////////
//
// pgAdmin III - PostgreSQL Tools
// RCS-ID:      $Id$
// Copyright (C) 2002 - 2006, The pgAdmin Development Team
// This software is released under the Artistic Licence
//
// precomp.h - All header files for compilers supporting precompiled headers
//
//////////////////////////////////////////////////////////////////////////

#ifdef WX_PRECOMP

#include "agent/dlgJob.h"
#include "agent/dlgSchedule.h"
#include "agent/dlgStep.h"
#include "agent/pgaJob.h"
#include "agent/pgaSchedule.h"
#include "agent/pgaStep.h"
#include "copyright.h"
#include "ctl/calbox.h"
#include "ctl/ctlComboBox.h"
#include "ctl/ctlListView.h"
#include "ctl/ctlSQLBox.h"
#include "ctl/ctlSQLGrid.h"
#include "ctl/ctlSQLResult.h"
#include "ctl/ctlTree.h"
#include "ctl/timespin.h"
#include "ctl/xh_calb.h"
#include "ctl/xh_ctlcombo.h"
#include "ctl/xh_ctltree.h"
#include "ctl/xh_sqlbox.h"
#include "ctl/xh_timespin.h"
#include "ctl/ctlSecurityPanel.h"
#include "dlg/dlgAddFavourite.h"
#include "dlg/dlgAggregate.h"
#include "dlg/dlgCast.h"
#include "dlg/dlgCheck.h"
#include "dlg/dlgClasses.h"
#include "dlg/dlgColumn.h"
#include "dlg/dlgConnect.h"
#include "dlg/dlgConversion.h"
#include "dlg/dlgDatabase.h"
#include "dlg/dlgDomain.h"
#include "dlg/dlgEditGridOptions.h"
#include "dlg/dlgFindReplace.h"
#include "dlg/dlgForeignKey.h"
#include "dlg/dlgFunction.h"
#include "dlg/dlgGroup.h"
#include "dlg/dlgHbaConfig.h"
#include "dlg/dlgIndex.h"
#include "dlg/dlgIndexConstraint.h"
#include "dlg/dlgLanguage.h"
#include "dlg/dlgMainConfig.h"
#include "dlg/dlgManageFavourites.h"
#include "dlg/dlgOperator.h"
#include "dlg/dlgPgpassConfig.h"
#include "dlg/dlgProperty.h"
#include "dlg/dlgRole.h"
#include "dlg/dlgRule.h"
#include "dlg/dlgSchema.h"
#include "dlg/dlgSelectConnection.h"
#include "dlg/dlgSequence.h"
#include "dlg/dlgServer.h"
#include "dlg/dlgTable.h"
#include "dlg/dlgTablespace.h"
#include "dlg/dlgTrigger.h"
#include "dlg/dlgType.h"
#include "dlg/dlgUser.h"
#include "dlg/dlgView.h"
#include "explainCanvas.h"
#include "frmAbout.h"
#include "frmBackup.h"
#include "frmConfig.h"
#include "frmEditGrid.h"
#include "frmExport.h"
#include "frmGrantWizard.h"
#include "frmHbaConfig.h"
#include "frmHelp.h"
#include "frmHint.h"
#include "frmIndexcheck.h"
#include "frmMain.h"
#include "frmMainConfig.h"
#include "frmMaintenance.h"
#include "frmOptions.h"
#include "frmPassword.h"
#include "frmPgpassConfig.h"
#include "frmQuery.h"
#include "frmReport.h"
#include "frmRestore.h"
#include "frmSplash.h"
#include "frmStatus.h"
#include "menu.h"
//#include "nodes/parsenodes.h"
//#include "parser/keywords.h"
//#include "parser/parse.h"
#include "pgAdmin3.h"
#include "pgAggregate.h"
#include "pgCast.h"
#include "pgCheck.h"
#include "pgCollection.h"
#include "pgColumn.h"
#include "pgConn.h"
#include "pgConstraints.h"
#include "pgConversion.h"
#include "pgDatabase.h"
#include "pgDatatype.h"
#include "pgDomain.h"
#include "pgForeignKey.h"
#include "pgFunction.h"
#include "pgGroup.h"
#include "pgIndex.h"
#include "pgIndexConstraint.h"
#include "pgLanguage.h"
#include "pgObject.h"
#include "pgOperator.h"
#include "pgOperatorClass.h"
#include "pgQueryThread.h"
#include "pgRole.h"
#include "pgRule.h"
#include "pgSchema.h"
#include "pgSequence.h"
#include "pgServer.h"
#include "pgSet.h"
#include "pgTable.h"
#include "pgTablespace.h"
#include "pgTrigger.h"
#include "pgType.h"
#include "pgUser.h"
#include "pgView.h"
#include "pgfeatures.h"
#include "utils/factory.h"
#include "utils/favourites.h"
#include "utils/md5.h"
#include "utils/misc.h"
#include "utils/pgDefs.h"
#include "utils/pgconfig.h"
#include "utils/sysLogger.h"
#include "utils/sysProcess.h"
#include "utils/sysSettings.h"
#include "utils/utffile.h"
#include "version.h"
#include "wxgridsel.h"


#endif
